// <auto-generated />
using System;
using GoodPlays.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodPlays.Infrastructure.Migrations
{
    [DbContext(typeof(GoodPlaysDbContext))]
    partial class GoodPlaysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodPlays.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Developer")
                        .HasColumnType("text")
                        .HasColumnName("developer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<string>("MetadataStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata_status");

                    b.Property<Guid?>("ParentGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_game_id");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sort_title");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentGameId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GameExternalId", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.HasKey("GameId", "Source");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("game_external_ids", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("game_genres", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("game_platforms", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modality");

                    b.Property<string>("SourceObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("source_object_key");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<decimal?>("HoursPlayed")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("hours_played");

                    b.Property<bool>("HoursPlayedLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hours_played_locked");

                    b.Property<string>("HoursPlayedSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hours_played_source");

                    b.Property<string>("PlatformExternalId")
                        .HasColumnType("text")
                        .HasColumnName("platform_external_id");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId", "Source")
                        .IsUnique()
                        .HasFilter("platform_external_id IS NULL");

                    b.HasIndex("UserId", "Source", "PlatformExternalId")
                        .IsUnique()
                        .HasFilter("platform_external_id IS NOT NULL");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("library_entries", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.PlatformConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("access_token_enc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_account_id");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshTokenEnc")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_enc");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<bool>("SyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_enabled");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Platform")
                        .IsUnique();

                    b.ToTable("platform_connections", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("ClerkId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<bool>("IsProfilePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_profile_public");

                    b.Property<string>("LibraryVisibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("library_visibility");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Game", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.Game", "ParentGame")
                        .WithMany("ChildGames")
                        .HasForeignKey("ParentGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGame");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GameExternalId", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.Game", "Game")
                        .WithMany("ExternalIds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GameGenre", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodPlays.Domain.Entities.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.GamePlatform", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodPlays.Domain.Entities.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.User", "User")
                        .WithMany("ImportJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.LibraryEntry", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.Game", "Game")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodPlays.Domain.Entities.User", "User")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.PlatformConnection", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.User", "User")
                        .WithMany("PlatformConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("GoodPlays.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GoodPlays.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Game", b =>
                {
                    b.Navigation("ChildGames");

                    b.Navigation("ExternalIds");

                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("LibraryEntries");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GoodPlays.Domain.Entities.User", b =>
                {
                    b.Navigation("ImportJobs");

                    b.Navigation("LibraryEntries");

                    b.Navigation("PlatformConnections");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
